export const ROUTE_CONSTANT = {
  THEME: "theme",
  DASHBOARD: "dashboard",
  APPOINTMENT: "appointment",
  PATIENT: "patient",
  DOCTOR_HOSPITAL: "doctor-hospital",
  REQUEST_APPROVAL: "request-approval",
  DELETE_REJECT_INACTIVE: "delete-reject-inactive",
  REVIEW: "review",
  SPECIALITY_PROCEDURE: "speciality-procedure",
  SETTINGS: "settings",
  SYNC_SITEMAP: "sync-sitemap",
  BLACKLIST: "blacklist",
  PRESCRIPTION: "prescription",
  KYC: "doctor-kyc",
  PAYMENTS: "payments",
  PAYOUTS: "payouts",
  REPORTS: "reports",
  FEATURE_ANNOUNCEMENTS: "feature-announcements",
  SURGERY: {
    SURGERY: "surgery",
    LEAD_LIST: "lead-list",
    ADD_SURGERY: "add-surgery",
    SURGERY_LIST: "list",
    TREATMENT_CITIES: "treatment-cities",
  },
};
